// pursor — CI Output Formatters.
//
// Converts a sweep summary into:
//   - JUnit XML  (sweep.junit.xml)  — CI pipeline integration
//   - GitHub Actions annotations  (sweep.github.json)
//   - Markdown summary            (sweep.md)
//
// Call writeCiOutput(summary) at the end of a sweep to write all three
// sidecars alongside sweep.json.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { escapeHtml } from "./util.js";

// ─── JUnit XML ───────────────────────────────────────────────────────────
// Produces a minimal JUnit-compatible XML that GitLab CI, Jenkins, CircleCI,
// and other CI runners understand.

function renderJUnitXml(summary) {
  const { steps, name, ts, outDir } = summary;
  const suiteName = escapeXml(name || "pursor-sweep");
  const tests = steps.length;
  const failures = steps.filter(s => !s.ok).length;
  const time = (steps.reduce((s, t) => s + (t.ms || 0), 0) / 1000).toFixed(3);

  const testcases = steps.map(s => {
    const className = escapeXml(`${s.op || "step"}` || "unknown");
    const testName = escapeXml(s.name || `step-${s.i}`);
    const fileAttr = s.meta?.out ? ` file="${escapeXml(s.meta.out)}"` : "";
    let extra = "";
    if (!s.ok) {
      const msg = escapeXml(s.error || "unknown error");
      const meta = s.meta ? escapeXml(JSON.stringify(s.meta, null, 2).slice(0, 500)) : "";
      extra = `\n      <failure message="${msg}">${meta ? `\n        <![CDATA[${meta}]]>\n      ` : ""}</failure>`;
    }
    return `    <testcase classname="${className}" name="${testName}" time="${((s.ms || 0) / 1000).toFixed(3)}"${fileAttr}>${extra}
    </testcase>`;
  }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="${suiteName}" tests="${tests}" failures="${failures}" errors="0" time="${time}" timestamp="${escapeXml(summary.ts || "")}">
${testcases}
</testsuite>`;
}

function escapeXml(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

// ─── GitHub Actions (JSON annotations) ───────────────────────────────────
// Each annotation: { filename, fileLine, annotation_level, message, title }

function renderGitHubAnnotations(summary) {
  const annotations = [];
  for (const s of summary.steps) {
    if (s.ok) continue;
    annotations.push({
      filename: s.meta?.out || s.name || `step-${s.i}`,
      fileLine: 1,
      annotation_level: "failure",
      title: `pursor: ${s.name || `step-${s.i}`}`,
      message: s.error || "Step failed",
      raw_details: s.meta ? JSON.stringify(s.meta) : "",
    });
  }
  // Also add warnings for diffs with high diffPct
  for (const s of summary.steps) {
    if (s.ok && s.meta?.numDiff > 0 && s.meta?.diffPct > 1) {
      annotations.push({
        filename: s.meta.out || s.name || `step-${s.i}`,
        fileLine: 1,
        annotation_level: "warning",
        title: `pursor: diff > 1%`,
        message: `${s.name}: ${s.meta.diffPct}% pixels differ from reference`,
        raw_details: JSON.stringify(s.meta),
      });
    }
  }
  return { annotations };
}

// ─── Markdown Summary ────────────────────────────────────────────────────

function renderMarkdownSummary(summary) {
  const lines = [
    `# pursor Sweep: ${summary.name || "(unnamed)"}`,
    ``,
    `**Plan:** \`${summary.plan || "?"}\``,
    `**Date:** ${summary.ts || "?"}`,
    `**Steps:** ${summary.steps.length}`,
    ``,
    `## Results`,
    ``,
    `| # | Name | Op | Status | Time |`,
    `|---|------|----|--------|------|`,
  ];

  for (const s of summary.steps) {
    const status = s.ok ? "✅ OK" : "❌ FAIL";
    const time = `${s.ms || 0}ms`;
    lines.push(`| ${s.i} | ${escapeMd(s.name || "")} | \`${s.op || ""}\` | ${status} | ${time} |`);
  }

  // Failures detail
  const failed = summary.steps.filter(s => !s.ok);
  if (failed.length) {
    lines.push(``, `## Failures`, ``);
    for (const s of failed) {
      lines.push(`### ${s.i}. ${s.name || "unknown"}`);
      lines.push(``);
      lines.push(`**Error:** \`${escapeMd(s.error || "unknown")}\``);
      if (s.meta?.out) lines.push(`**Output:** \`${s.meta.out}\``);
      lines.push(``);
    }
  }

  // Diffs with non-zero diff
  const diffs = summary.steps.filter(s => s.ok && s.meta?.numDiff > 0);
  if (diffs.length) {
    lines.push(``, `## Diffs`, ``);
    for (const s of diffs) {
      lines.push(`| ${s.name} | ${s.meta.diffPct}% | ${s.meta.numDiff}/${s.meta.totalPx} pixels |`);
    }
    lines.push(``);
  }

  lines.push(`_Generated by pursor_`);
  return lines.join("\n");
}

function escapeMd(s) {
  return String(s ?? "").replace(/([_*[\]()~`>#+\-=|{}!.])/g, "\\$1");
}

// ─── Writer ──────────────────────────────────────────────────────────────

/**
 * Write CI-format output files alongside the sweep summary.
 *
 * @param {object} summary - Sweep summary object from runSweep()
 * @param {string} dir     - Output directory (same as sweep.json)
 * @returns {{ junit: string, github: string, markdown: string }} Written paths
 */
export function writeCiOutput(summary, dir) {
  if (!dir) dir = summary.outDir || ".";
  mkdirSync(dir, { recursive: true });
  const junitPath = join(dir, "sweep.junit.xml");
  const githubPath = join(dir, "sweep.github.json");
  const mdPath = join(dir, "sweep.md");

  writeFileSync(junitPath, renderJUnitXml(summary), "utf8");
  writeFileSync(githubPath, JSON.stringify(renderGitHubAnnotations(summary), null, 2), "utf8");
  writeFileSync(mdPath, renderMarkdownSummary(summary), "utf8");

  return { junit: junitPath, github: githubPath, markdown: mdPath };
}
